@extends('layouts.app')
@section('content')
<div class="hotel-page"><div class="gallery"><div class="main-photo"></div><div class="side-photo"></div><div class="side-photo second"></div></div>
<div class="hotel-layout"><main><p id="hotelLocation" class="eyebrow">LOADING HOTEL</p><h1 id="hotelName">Please wait…</h1><p class="description">Choose your dates to see live room availability and prices.</p><h2>Available rooms</h2><div id="roomResults">Loading…</div></main>
<aside class="booking-box"><h3>Your stay</h3><label>Check-in<input id="detailCheckIn" type="date"></label><label>Check-out<input id="detailCheckOut" type="date"></label><label>Guest name<input id="guestName" placeholder="Full name"></label><label>Email<input id="guestEmail" type="email" placeholder="you@example.com"></label><hr><p id="bookingSummary">Select a room to continue</p><h2 id="bookingTotal">—</h2><button id="reserveButton" disabled>Reserve now</button><small>Secure booking · Final payment method is selected next</small></aside></div></div>
<script>
const slug=location.pathname.split('/').pop(),params=new URLSearchParams(location.search);let hotel=null,selected=null;
detailCheckIn.value=params.get('check_in')||'';detailCheckOut.value=params.get('check_out')||'';
async function loadHotel(){const r=await fetch('/api/public/hotels/'+encodeURIComponent(slug),{headers:{Accept:'application/json'}});if(!r.ok){hotelName.textContent='Hotel not found';return;}const d=await r.json();hotel=d.hotel;hotelName.textContent=hotel.name;hotelLocation.textContent=(hotel.city||'BANGLADESH').toUpperCase();loadRooms();}
async function loadRooms(){if(!detailCheckIn.value||!detailCheckOut.value){roomResults.textContent='Select check-in and check-out dates.';return;}const r=await fetch('/api/public/hotels/'+hotel.id+'/rooms?check_in='+detailCheckIn.value+'&check_out='+detailCheckOut.value,{headers:{Accept:'application/json'}});const d=await r.json();const rooms=d.rooms||[];roomResults.innerHTML=rooms.length?rooms.map(x=>'<div class="room-row"><div class="room-thumb"></div><div><h3>'+x.name+'</h3><p>Capacity: '+x.capacity+' guests</p><small>Live availability checked for your dates</small></div><div><strong>From ৳'+x.base_price+'</strong><button data-room="'+x.id+'">Select</button></div></div>').join(''):'No rooms available for these dates.';document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>selectRoom(Number(b.dataset.room),rooms));}
function selectRoom(id,rooms){selected=rooms.find(x=>x.id===id);bookingSummary.textContent=selected.name+' selected';bookingTotal.textContent='Price calculated from live dates';reserveButton.disabled=false;}
detailCheckIn.onchange=loadRooms;detailCheckOut.onchange=loadRooms;
reserveButton.onclick=async()=>{if(!selected||!guestName.value||!guestEmail.value){alert('Please select a room and enter guest details.');return;}reserveButton.disabled=true;reserveButton.textContent='Creating booking…';const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({property_id:hotel.id,room_type_id:selected.id,check_in:detailCheckIn.value,check_out:detailCheckOut.value,guest_name:guestName.value,guest_email:guestEmail.value})});const d=await r.json();if(!r.ok){alert(d.message||'Booking could not be created.');reserveButton.disabled=false;reserveButton.textContent='Reserve now';return;}location.href='/booking/'+d.booking.id+'/payment';};
loadHotel();
</script>
@endsection