#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$input = new ArgvInput;
$output = new ConsoleOutput;

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$status = $kernel->handle($input, $output);
$kernel->terminate($input, $status);
exit($status);
