@extends('layouts.app')

@section('content')
<style>
.refund-page{max-width:1280px;margin:0 auto;padding:32px 20px;color:#1f2937}.refund-page *{box-sizing:border-box}.refund-head{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:24px}.refund-kicker{margin:0 0 6px;color:#0f766e;font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.refund-page h2{margin:0;font-size:28px}.refund-sub{margin:7px 0 0;color:#64748b}.refund-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:22px}.refund-stat,.refund-panel{background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 4px 16px rgba(15,23,42,.05)}.refund-stat{padding:18px}.refund-label{font-size:13px;color:#64748b}.refund-value{font-size:25px;font-weight:700;margin-top:7px;color:#0f172a}.refund-panel{overflow:hidden}.refund-panel-head{padding:18px 22px;border-bottom:1px solid #e5e7eb;display:flex;justify-content:space-between;align-items:center;gap:15px}.refund-title{font-size:18px;font-weight:700}.refund-filter select{min-width:210px;height:42px;padding:0 12px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.refund-table-wrap{overflow-x:auto}.refund-table{width:100%;border-collapse:collapse;min-width:900px}.refund-table th{background:#f8fafc;color:#475569;font-size:12px;text-transform:uppercase;letter-spacing:.04em;text-align:left}.refund-table th,.refund-table td{padding:15px 18px;border-bottom:1px solid #e5e7eb}.refund-table tr:last-child td{border-bottom:0}.refund-amount{font-weight:700;color:#0f172a}.refund-reason{max-width:300px;color:#64748b}.refund-badge{display:inline-flex;padding:5px 10px;border-radius:999px;font-size:12px;font-weight:700}.refund-pending{background:#fef3c7;color:#92400e}.refund-approved{background:#dbeafe;color:#1d4ed8}.refund-processed{background:#dcfce7;color:#15803d}.refund-rejected{background:#fee2e2;color:#b91c1c}.refund-other{background:#e5e7eb;color:#475569}.refund-actions{display:flex;gap:7px}.refund-actions button{border:0;border-radius:8px;padding:8px 12px;font-size:13px;font-weight:600;cursor:pointer}.refund-approve{background:#16a34a;color:#fff}.refund-reject{background:#fff;color:#dc2626;border:1px solid #dc2626!important}.refund-empty{text-align:center;color:#94a3b8;padding:34px!important}.refund-footer{padding:16px 20px;border-top:1px solid #e5e7eb}@media(max-width:700px){.refund-page{padding:20px 12px}.refund-head{align-items:flex-start;flex-direction:column}.refund-page h2{font-size:23px}.refund-stats{grid-template-columns:1fr}.refund-panel-head{align-items:flex-start;flex-direction:column;width:100%}.refund-filter,.refund-filter select{width:100%}}
</style>

<div class="refund-page">
    <div class="refund-head"><div><p class="refund-kicker">Administration</p><h2>Refund Management</h2><p class="refund-sub">Review customer refund requests and manage approval decisions.</p></div><a href="{{ route('dashboard.admin') }}" class="btn btn-outline-secondary">← Dashboard</a></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    @php $refundItems=collect($refunds->items()); @endphp
    <div class="refund-stats"><div class="refund-stat"><div class="refund-label">Pending Review</div><div class="refund-value">{{ $refundItems->where('status','pending_review')->count() }}</div></div><div class="refund-stat"><div class="refund-label">Approved</div><div class="refund-value">{{ $refundItems->where('status','approved')->count() }}</div></div><div class="refund-stat"><div class="refund-label">Processed / Rejected</div><div class="refund-value">{{ $refundItems->whereIn('status',['processed','rejected'])->count() }}</div></div></div>
    <div class="refund-panel"><div class="refund-panel-head"><div class="refund-title">Refund Requests</div><form class="refund-filter" method="GET"><select name="status" onchange="this.form.submit()"><option value="">All statuses</option>@foreach(['pending_review','approved','rejected','processed'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucfirst(str_replace('_',' ',$s)) }}</option>@endforeach</select></form></div>
    <div class="refund-table-wrap"><table class="refund-table"><thead><tr><th>ID</th><th>Booking</th><th>Amount</th><th>Status</th><th>Reason</th><th>Action</th></tr></thead><tbody>
    @forelse($refunds as $refund)
    <tr><td><strong>#{{ $refund->id }}</strong></td><td>#{{ $refund->booking_id }}</td><td class="refund-amount">৳ {{ number_format($refund->amount,2) }}</td><td>@php $refundClass='refund-other'; if($refund->status==='pending_review')$refundClass='refund-pending'; elseif($refund->status==='approved')$refundClass='refund-approved'; elseif($refund->status==='processed')$refundClass='refund-processed'; elseif($refund->status==='rejected')$refundClass='refund-rejected'; @endphp<span class="refund-badge {{ $refundClass }}">{{ ucfirst(str_replace('_',' ',$refund->status)) }}</span></td><td class="refund-reason">{{ $refund->reason ?: 'No reason provided' }}</td><td>@if($refund->status==='pending_review')<div class="refund-actions"><form method="POST" action="{{ route('admin.refunds.approve',$refund) }}">@csrf<button class="refund-approve">Approve</button></form><form method="POST" action="{{ route('admin.refunds.reject',$refund) }}">@csrf<button class="refund-reject">Reject</button></form></div>@else<span class="text-muted">No action</span>@endif</td></tr>
    @empty<tr><td colspan="6" class="refund-empty">No refund requests found.</td></tr>@endforelse
    </tbody></table></div>@if(method_exists($refunds,'links'))<div class="refund-footer">{{ $refunds->links() }}</div>@endif</div>
</div>
@endsection
